{
 "title": "KES Dashboard",
 "description": "KES Grafana Dashboard - https://hanzo.ai/",
 "tags": [ "hanzos3" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "scrape_jobs", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(kes_system_up_time{job=~\"$scrape_jobs\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "total CPUs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kes_system_num_cpu{job=~\"$scrape_jobs\"})"
    }
   ]
  },
  {
   "title": "Used CPUs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kes_system_num_cpu_used{job=~\"$scrape_jobs\"})"
    }
   ]
  },
  {
   "title": "Number of Threads",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kes_system_num_threads{job=~\"$scrape_jobs\"})"
    }
   ]
  },
  {
   "title": "Active Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kes_http_request_active{job=~\"$scrape_jobs\"})"
    }
   ]
  },
  {
   "title": "Number of Heap Objects",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kes_system_mem_heap_objects{job=~\"$scrape_jobs\"})"
    }
   ]
  },
  {
   "title": "Heap Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kes_system_mem_heap_used{job=~\"$scrape_jobs\"})"
    }
   ]
  },
  {
   "title": "Stack Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kes_system_mem_stack_used{job=~\"$scrape_jobs\"})"
    }
   ]
  },
  {
   "title": "Log Audit Events",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kes_log_audit_events{job=~\"$scrape_jobs\"})"
    }
   ]
  },
  {
   "title": "Log Error Events",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kes_log_error_events{job=~\"$scrape_jobs\"})"
    }
   ]
  },
  {
   "title": "Request / Response Times",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kes_http_response_time_bucket{job=~\"$scrape_jobs\"}",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}