version: 2
project_name: kes

release:
   name_template: Release {{ replace .CommitDate ":" "-" }}

   github:
    owner: hanzos3
    name: kes

before:
  hooks:
    - go mod tidy
    - bash -c 'git diff --quiet || (echo "Repo contains modified files. Run git checkout" && exit 1)'
    - bash -c '[[ {{ .Tag }} == {{ replace .CommitDate ":" "-" }} ]] || (echo Invalid release tag. Run git tag {{ replace .CommitDate ":" "-" }} && exit 1)'

builds:
  -
    main: ./cmd/kes
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: amd64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
      - -buildvcs=true
    ldflags:
      - "-s -w"

archives:
  -
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    format: binary

nfpms:
  -
    vendor: Hanzo AI, Inc.
    homepage: https://github.com/hanzos3/kes
    maintainer: Hanzo AI <dev@hanzo.ai>
    description: KES is a stateless and distributed key-management system for high-performance applications
    license: GNU Affero General Public License v3.0
    formats:
      - deb
      - rpm

signs:
  -
    signature: "${artifact}.minisig"
    cmd: "sh"
    args:
      - '-c'
      - 'minisign -s /media/${USER}/hanzos3/minisign.key -Sm ${artifact} < /media/${USER}/hanzos3/minisign-passphrase'
    artifacts: all

snapshot:
  version_template: '{{ replace .CommitDate ":" "-" }}'

changelog:
  sort: asc

dockers:
- image_templates:
  - hanzos3/kes:{{ replace .CommitDate ":" "-" }}-amd64
  use: buildx
  dockerfile: Dockerfile
  extra_files:
    - LICENSE
    - CREDITS
  build_flag_templates:
  - '--platform=linux/amd64'
  - '--build-arg=TAG={{ replace .CommitDate ":" "-" }}'
- image_templates:
  - quay.io/hanzos3/kes:{{ replace .CommitDate ":" "-" }}-amd64
  use: buildx
  dockerfile: Dockerfile
  extra_files:
    - LICENSE
    - CREDITS
  build_flag_templates:
  - '--platform=linux/amd64'
  - '--build-arg=TAG={{ replace .CommitDate ":" "-" }}'
- image_templates:
  - hanzos3/kes:{{ replace .CommitDate ":" "-" }}-arm64
  use: buildx
  goarch: arm64
  dockerfile: Dockerfile
  extra_files:
    - LICENSE
    - CREDITS
  build_flag_templates:
  - '--platform=linux/arm64'
  - '--build-arg=TAG={{ replace .CommitDate ":" "-" }}'
- image_templates:
  - quay.io/hanzos3/kes:{{ replace .CommitDate ":" "-" }}-arm64
  use: buildx
  goarch: arm64
  dockerfile: Dockerfile
  extra_files:
    - LICENSE
    - CREDITS
  build_flag_templates:
  - '--platform=linux/arm64'
  - '--build-arg=TAG={{ replace .CommitDate ":" "-" }}'
docker_manifests:
- name_template: hanzos3/kes:{{ replace .CommitDate ":" "-" }}
  image_templates:
  - hanzos3/kes:{{ replace .CommitDate ":" "-" }}-amd64
  - hanzos3/kes:{{ replace .CommitDate ":" "-" }}-arm64
- name_template: quay.io/hanzos3/kes:{{ replace .CommitDate ":" "-" }}
  image_templates:
  - quay.io/hanzos3/kes:{{ replace .CommitDate ":" "-" }}-amd64
  - quay.io/hanzos3/kes:{{ replace .CommitDate ":" "-" }}-arm64
- name_template: hanzos3/kes:latest
  image_templates:
  - hanzos3/kes:{{ replace .CommitDate ":" "-" }}-amd64
  - hanzos3/kes:{{ replace .CommitDate ":" "-" }}-arm64
